site_name: Lumoumou' Zone
site_url: https://LuciferCCC.github.io
site_description: Recording some Experience
site_author: lumoumou
repo_name: LiciferCCC.github.io
repo_url: https://github.com/LuciferCCC
copyright: "Copyright &copy; 2022.01 - 2023 lumoumou"

theme:
  logo: assets/logo.svg
  favicon: assets/logo.svg
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    # - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.tabs.link


  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple


plugins:
  - search
  - git-revision-date-localized:
      enabled: true
      type: date
      enable_creation_date: true


nav:
  - 简介: blogs/post/主页简介.md

  - 算法基础课:
    - 第一章 基础算法: blogs/post/算法基础课/第一章 基础算法.md
    - 第二章 数据结构: blogs/post/算法基础课/第二章 数据结构.md
    - 第三章 搜索与图论: blogs/post/算法基础课/第三章 搜索与图论.md

  - 算法提高课:
    - 第一章 基础算法(0): blogs/post/算法提高课/第一章 基础算法(0).md
      
  - 机器学习:
    - 第一章 线性回归: blogs/post/机器学习/第一章 线性回归/课堂笔记.md

  - 目标检测:
    - YOLO基础: blogs/post/目标检测/YOLO基础.md

  - 计算机专业基础课程:
    - 计算机网络: 
      - 第一章 计算机网络体系结构: blogs/post/计算机专业基础课程/计算机网络/第一章 计算机网络体系结构.md
      - 第二章 物理层: blogs/post/计算机专业基础课程/计算机网络/第二章 物理层.md
    - 操作系统: blogs/post/计算机专业基础课程/操作系统.md
    - 数据结构: blogs/post/计算机专业基础课程/数据结构.md
    - 计算机组成原理: blogs/post/计算机专业基础课程/计算机组成原理.md

  - AcWing工程课——Django:
    - 项目简介: blogs/post/AcWing工程课——Django/简介.md
    - 第一章 项目基本设置: blogs/post/AcWing工程课——Django/一、项目基本设置.md
    - 第二章 创建菜单界面: blogs/post/AcWing工程课——Django/二、创建菜单界面.md
    - 第三章 创建游戏界面: blogs/post/AcWing工程课——Django/三、创建游戏界面.md
    - 第四章 部署nginx和对接AcApp: blogs/post/AcWing工程课——Django/四、部署nginx和对接AcApp.md
    - 第五章 创建账号系统: blogs/post/AcWing工程课——Django/五、创建账号系统.md
    - 第六章 配置AcWing一键登录: blogs/post/AcWing工程课——Django/六、配置AcWing一键登录.md
    - 第七章 实现联机对战系统: blogs/post/AcWing工程课——Django/七、实现联机对战系统.md

  - Linux: 
    - 常用指令:
      - Linux: blogs/post/Linux/常用指令/Linux.md
      - Git: blogs/post/Linux/常用指令/git.md
      - Docker: blogs/post/Linux/常用指令/docker.md
      - Shell: blogs/post/Linux/常用指令/shell.md
      

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - footnotes
  - pymdownx.caret:
      smart_insert: true
      insert: true
      superscript: true
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.mark:
      smart_mark: true
  - pymdownx.smartsymbols

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  homepage: https://LuciferCCC.github.io